mylittlecloud/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.core.urlresolvers import reverse_lazy

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^license/$', TemplateView.as_view(template_name='license.html'), name='license'),
    url(r'^uploads/', include('uploads.urls')),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {
        #'next': reverse_lazy('home'),
    }, name="login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {
        'next_page': reverse_lazy('home'),
    }, name="logout"),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

uploads/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = patterns('uploads.views',
    # Examples:
    url(r'^list$', "list_own", name='uploads_list'),
    url(r'^create/$', login_required(views.AreaCreate.as_view()), name='uploads_create'),
    url(r'^edit/(?P<pk>\d+)/$', login_required(views.AreaUpdate.as_view()), name='uploads_edit'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(views.AreaDelete.as_view()), name='uploads_delete'),
    url(r'^area/(?P<uuid>[^/]+)/$', 'public', name='uploads_public'),
    url(r'^area/(?P<uuid>[^/]+)/delete/$', 'delete_file', name='uploads_delete_file'),
)

layout/models.py
from django.db import models

# Create your models here.

uploads/models.py
# coding: utf-8
from __future__ import absolute_import
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
import os.path

class Area(models.Model):
    """
    A sharable file upload area
    """
    owner = models.ForeignKey(User)
    name = models.CharField(_("Name"), max_length=32)
    uuid = models.CharField(_("UUID"), max_length=48, unique=True)
    expiry = models.DateField(_("Expiration date"))
    max_size = models.IntegerField(_("Max size (MB)"), default=64)
    description = models.TextField()

    @property
    def expired(self):
        """
        True if the area is expired
        """
        return self.expiry < now().date()

    @property
    def size_percent(self):
        """
        Return the space currently in use as a percentage of the total size
        """
        return int(100.0 * self.size_used / (self.max_size * 1024 * 1024))

    @property
    def size_used(self):
        """
        Return the space currently in use for this area
        """
        return sum(f.file.size for f in self.files.all())

    class Meta:
        unique_together = ["owner", "name"]

def get_upload_path(instance, filename):
    return os.path.join(instance.area.owner.username, instance.area.uuid, os.path.basename(filename))

class File(models.Model):
    """
    An uploaded file
    """
    area = models.ForeignKey(Area, related_name="files")
    file = models.FileField(upload_to=get_upload_path)

layout/views.py
# Create your views here.

uploads/views.py
# coding: utf-8
from __future__ import absolute_import
from django.utils.translation import ugettext as _
from django import http, template, forms
from django.shortcuts import redirect, render, render_to_response, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.formsets import formset_factory
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
import uploads.models as umodels
from django.utils.timezone import now
import datetime
import os.path

@login_required
def list_own(request):
    areas = list(umodels.Area.objects.filter(owner=request.user).order_by("name"))
    # , expiry__gte=now().date()
    areas.sort(key=lambda a:a.expired)
    return render(request, "uploads/list.html", {
        "areas": areas,
    })

class UploadForm(forms.ModelForm):
    class Meta:
        model = umodels.File
        exclude = ('area',)

def public(request, uuid):
    area = get_object_or_404(umodels.Area, uuid=uuid)
    if area.expired:
        return http.HttpResponseNotFound("Requested area has expired")

    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.area = area
            f.save()
    else:
        form = UploadForm()

    files = []
    for f in area.files.order_by("file"):
        files.append({
            "id": f.id,
            "url": f.file.url,
            "name": os.path.basename(f.file.name),
            "size": f.file.size,
        })


    return render(request, "uploads/public.html", {
        "area": area,
        "form": form,
        "files": files,
    })

def delete_file(request, uuid):
    if request.method != "POST":
        return http.HttpResponseBadRequest("Only POST is accepted")

    area = get_object_or_404(umodels.Area, uuid=uuid)
    f = get_object_or_404(umodels.File, pk=request.POST["file"])
    if f.area != area:
        return http.HttpResponseNotFound("Requested file not found")

    f.file.delete()
    f.delete()

    return redirect('uploads_public', uuid=area.uuid)


class AreaForm(forms.ModelForm):
    expiry = forms.DateField(required=True,
                             initial=now,
                             input_formats=("%Y-%m-%d",),
                             widget=forms.DateInput(format="%Y-%m-%d"))

class AreaCreateForm(AreaForm):
    class Meta:
        model = umodels.Area
        exclude = ('owner', 'uuid')

    def validate_unique(self):
        exclude = self._get_validation_exclusions()
        exclude.remove("owner")
        try:
            self.instance.validate_unique(exclude=exclude)
        except forms.ValidationError, e:
            self._update_errors(e.message_dict)

class AreaEditForm(AreaForm):
    class Meta:
        model = umodels.Area
        exclude = ('owner', 'name', 'uuid')

    def validate_unique(self):
        exclude = self._get_validation_exclusions()
        exclude.remove("owner")
        try:
            self.instance.validate_unique(exclude=exclude)
        except forms.ValidationError, e:
            self._update_errors(e.message_dict)

class AreaCreate(CreateView):
    model = umodels.Area
    form_class = AreaCreateForm
    success_url = reverse_lazy("uploads_list")

    def get_initial(self):
        initial = super(AreaCreate, self).get_initial().copy()
        initial["expiry"] = now().date() + datetime.timedelta(days=30)
        return initial

    def get_form(self, form_class):
        form = super(AreaCreate, self).get_form(form_class)
        form.instance.owner = self.request.user
        return form

    def form_valid(self, form):
        import uuid
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.uuid = str(uuid.uuid4())
        self.object.save()
        return redirect(self.get_success_url())

class AreaUpdate(UpdateView):
    model = umodels.Area
    form_class = AreaEditForm
    success_url = reverse_lazy("uploads_list")

class AreaDelete(DeleteView):
    model = umodels.Area
    success_url = reverse_lazy("uploads_list")

layout/templates/base.html
{% load i18n %}
{% load url from future %}
{% comment %}{% load try_to_include %}{% endcomment %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head_resources %}
  <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" media="screen">
  <script src="{{STATIC_URL}}js/jquery-2.0.0.min.js"></script>
  <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
  {% endblock %}
  <title>{% block title %}My Little Cloud{% endblock %}</title>
</head>
<body>
  <header class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="{% url 'home' %}">
          My Little Cloud
          <img src="{{STATIC_URL}}img/logo.png"></img>
        </a>
        <ul class="nav">
          <li class="{% block navclass_uploads %}{% endblock %}"><a href="{% url 'uploads_list' %}">Uploads</a></li>
          {% if user.is_authenticated %}
          <li><a href="TODO">{{user}}</a></li>
          <li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">{% trans "Login" %}</a></li>
          {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </header>

  <div class="container">
    <!-- Message handling -->
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert {{ message.tags }}"{% endif %}>
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      {{ message }}
    </div>
    {% endfor %}

    <script type="text/javascript">
      $(document).ready(function() {
          $(".alert").alert();
      });
    </script>
    {% endif %}
    <!-- End of message handling -->
    
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <footer>
    <div class="container">
      <p><small>
      Copyright © 2011-2012 Enrico Zini &lt;enrico@debian.org&gt;. See <a href="{% url 'license' %}">license</a> terms.
      Source code is <a href="https://gitorious.org/mylittlecloud">available</a>.
      </small></p>
    </div>
  </footer>
</body>
</html>

layout/templates/form-horizontal.html
  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
  {{ form.non_field_errors }}
  {% for field in form.visible_fields %}
    <div class="control-group">
      <label for="id_{{field.html_name}}" class="control-label">{{field.label}}</label>
      <div class="controls">
        {{field}}
        {{field.errors}}
      </div>
    </div>
  {% endfor %}

mylittlecloud/templates/home.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

<div class="hero-unit">
  <h1>My little cloud</h1>
  <p>Fixing internet papercuts since 2013.</p>
  <p>
  {% if user.is_authenticated %}
  <a class="btn btn-primary btn-large" href="{% url 'uploads_list' %}">Uploads</a>
  {% endif %}
  </p>
</di>

{% endblock %}

mylittlecloud/templates/license.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

<div>
  <h1>License</h1>

  <pre>
  Copyright (C) 2013  Enrico Zini &lt;enrico@enricozini.org&gt;

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.
  </pre>
</div>

{% endblock %}

uploads/templates/uploads/area_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block navclass_uploads %}active{% endblock %}

{% block content %}
<p>{% trans 'Are you sure that you would like to delete this area?' %}</p>

<div id="comment_preview">{{object.name}}</div>

<form method="POST" action=".">{% csrf_token %}
    <input type="submit" value="Yes"> <a href="{{ next }}">No</a>
</form>
{% endblock %}

uploads/templates/uploads/area_form.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block navclass_uploads %}active{% endblock %}

{% block head_resources %}
{{block.super}}
<link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet"/>
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
<script>
  $(function() {
    $("#id_expiry").datepicker({format: "yyyy-mm-dd"})
  });
</script>
{{form.media}}
{% endblock %}

{% block title %}{% trans "Area" %}{% endblock %}

{% block content %}
<form action="." method="POST">{% csrf_token %}
{{form}}
<input type="submit"></input>
</form>
{% endblock %}

uploads/templates/uploads/list.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block head_resources %}
{{block.super}}
<style>
td.size div.progress {
  margin: 0
}
div.size-text {
  text-align: center;
}
</style>
{% endblock %}

{% block navclass_uploads %}active{% endblock %}

{% block title %}{% trans 'File areas' %}{% endblock %}

{% block content %}

<h1>File areas</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>{% trans 'Name' %}</th>
      <th>{% trans 'Disk space' %}</th>
      <th>{% trans 'Expires' %}</th>
      <th>{% trans 'Actions' %}</th>
    </tr>
  </thead>
  <tbody>
  {% for a in areas %}
  <tr {% if a.expired %}class="warning"{% endif %}>
    <td><a href="{% url 'uploads_public' uuid=a.uuid %}">{{a.name}}</a></td>
    <td class="size">
      <div class="progress progress-striped">
        <div class="bar" style="width: {{a.size_percent}}%">
        </div>
      </div>
      <div class="size-text">{{a.size_used|filesizeformat}} / {{a.max_size}} MB</div>
    </td>
    <td>{{a.expiry}}</td>
    <td><a href="{% url 'uploads_edit' pk=a.pk %}">edit</a> <a href="{% url 'uploads_delete' pk=a.pk %}">delete</a></td>
  </tr>
  {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="5">
        <a href="{% url 'uploads_create' %}">{% trans "Create new file area" %}</a>
      </td>
    </tr>
  </tfoot>
</table>

{% endblock %}

uploads/templates/uploads/public.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block head_resources %}
{{block.super}}
<style>
form.action-form {
  margin: 0;
  padding: 0;
}

form.upload-form {
  margin: 0;
  padding: 0;
}
form.upload-form label {
  display: inline;
  vertical-align: middle;
}
div.progress {
  margin: 0
}
</style>
{% endblock %}

{% block navclass_uploads %}active{% endblock %}

{% block content %}

<h1>{{area.name}}</h1>

<p class="lead">{{area.description}}</p>

<h3>{% blocktrans with user=area.owner.username %}Files for {{user}}{% endblocktrans %}</h3>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for f in files %}
    <tr>
      <td><a href="{{f.url}}">{{f.name}}</a></td>
      <td>{{f.size|filesizeformat}}</td>
      <td>
        <form action="{% url 'uploads_delete_file' uuid=area.uuid %}" method="post" class="action-form">{% csrf_token %}
          <input type="hidden" name="file" value="{{f.id}}">
          <input type="submit" value="{% trans 'Delete' %}">
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>
        <form id="upload-form" class="upload-form" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
          {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
          {{ form.non_field_errors }}
          <p>
          <label for="id_{{form.file.html_name}}">{% trans 'New file:' %}</label>
          {{form.file}}
          {{form.file.errors}}
          </p>
        </form>
      </td>
      <td></td>
      <td>
        <button form="upload-form" type="submit" class="btn btn-primary">{% trans 'Upload' %}</button>
      </td>
    </tr>
    <tr>
      <td colspan="3">
        <div class="progress progress-striped">
          <div class="bar" style="width: {{area.size_percent}}%">
          </div>
        </div>
        {% blocktrans with used=area.size_used|filesizeformat max=area.max_size expiry=area.expiry %}
          Used: {{used}} / {{max}} MB, expires: {{expiry}}
        {% endblocktrans %}
      </td>
    </tr>
  </tfoot>
</table>

{% endblock %}